import type { CatalogTemplate } from "./types";

function svgPreview(label: string, a: string, b: string) {
  const svg = `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 1080 1920'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop offset='0%' stop-color='${a}'/><stop offset='100%' stop-color='${b}'/></linearGradient></defs><rect width='1080' height='1920' fill='url(#g)'/><rect x='48' y='48' width='984' height='1824' rx='42' fill='none' stroke='rgba(255,255,255,.25)'/><text x='540' y='980' text-anchor='middle' fill='white' font-family='Inter,Arial,sans-serif' font-size='68' font-weight='800'>${label}</text></svg>`;
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}

export const VIDEO_TEMPLATE_CATALOG: CatalogTemplate[] = [
  {
    slug: "luxury-vertical-reveal",
    name: "Luxury Vertical Reveal",
    type: "SHORT",
    previewImage: svgPreview("Luxury Reveal", "#0B1220", "#9A6B20"),
    sortOrder: 1,
    config: {
      engineVersion: 1,
      duration: 15,
      slideDurationMs: 3200,
      transition: "zoom-fade",
      animation: "scale-in",
      textStyle: "luxury",
      kenBurns: true,
      grainOpacity: 0.04,
      imageSlots: 6,
      overlay: { titlePosition: "center", pricePosition: "bottom", locationPosition: "bottom" },
      theme: { overlay: "gradient-dark", titlePosition: "center", typography: "serif-elegant", accent: "amber" },
      showPriceBadge: true,
    },
  },
  {
    slug: "tiktok-premium-real-estate",
    name: "TikTok Premium Real Estate",
    type: "SHORT",
    previewImage: svgPreview("TikTok Premium", "#071A2D", "#00B8D9"),
    sortOrder: 2,
    config: {
      engineVersion: 1,
      duration: 15,
      slideDurationMs: 2800,
      transition: "slide-fade",
      animation: "scale-in",
      textStyle: "bold-center",
      imageSlots: 6,
      overlay: { titlePosition: "center", pricePosition: "bottom", locationPosition: "bottom" },
      theme: {
        overlay: "vignette-spotlight",
        titlePosition: "center",
        typography: "sans-bold",
        accent: "cyan",
      },
      showPriceBadge: true,
    },
  },
  {
    slug: "dark-gold-elite",
    name: "Dark Gold Elite",
    type: "SHORT",
    previewImage: svgPreview("Dark Gold Elite", "#090909", "#9B7A2A"),
    sortOrder: 3,
    config: {
      engineVersion: 1,
      duration: 18,
      slideDurationMs: 4000,
      transition: "gold-fade",
      animation: "fade",
      textStyle: "luxury",
      kenBurns: true,
      imageSlots: 5,
      overlay: { titlePosition: "bottom", pricePosition: "bottom", locationPosition: "bottom" },
      theme: { overlay: "gold-frame", titlePosition: "bottom", typography: "display-gold", accent: "gold" },
      showPriceBadge: true,
    },
  },
  {
    slug: "skyline-flash-short",
    name: "Skyline Flash Short",
    type: "SHORT",
    previewImage: svgPreview("Skyline Flash", "#081C3D", "#6C63FF"),
    sortOrder: 4,
    config: {
      engineVersion: 1,
      duration: 14,
      slideDurationMs: 2600,
      transition: "blur-slide",
      animation: "slide-left",
      textStyle: "bold-center",
      imageSlots: 6,
      overlay: { titlePosition: "top", pricePosition: "bottom", locationPosition: "bottom" },
      theme: { overlay: "neon-edge", titlePosition: "top", typography: "sans-bold", accent: "cyan" },
      showPriceBadge: true,
    },
  },
  {
    slug: "premium-swipe-short",
    name: "Premium Swipe Reels",
    type: "SHORT",
    previewImage: svgPreview("Premium Swipe", "#250C3F", "#F43F5E"),
    sortOrder: 5,
    config: {
      engineVersion: 1,
      duration: 16,
      slideDurationMs: 3000,
      transition: "slide-fade",
      animation: "slide-right",
      textStyle: "bold-center",
      imageSlots: 6,
      overlay: { titlePosition: "center", pricePosition: "bottom", locationPosition: "bottom" },
      theme: { overlay: "vignette-spotlight", titlePosition: "center", typography: "sans-bold", accent: "cyan" },
      showPriceBadge: true,
    },
  },
  {
    slug: "cinematic-property-showcase",
    name: "Cinematic Property Showcase",
    type: "LONG",
    previewImage: svgPreview("Cinematic Showcase", "#05070B", "#334155"),
    sortOrder: 6,
    config: {
      engineVersion: 1,
      duration: 60,
      slideDurationMs: 5400,
      transition: "cinematic-dissolve",
      animation: "scale-out",
      textStyle: "luxury",
      kenBurns: true,
      grainOpacity: 0.06,
      imageSlots: 10,
      overlay: { titlePosition: "bottom", pricePosition: "bottom", locationPosition: "bottom" },
      theme: { overlay: "letterbox-film", titlePosition: "bottom", typography: "serif-elegant", accent: "amber" },
      showPriceBadge: true,
      showChannelBranding: true,
    },
  },
  {
    slug: "minimal-clean-architecture",
    name: "Minimal Clean Architecture",
    type: "LONG",
    previewImage: svgPreview("Minimal Clean", "#E2E8F0", "#94A3B8"),
    sortOrder: 7,
    config: {
      engineVersion: 1,
      duration: 45,
      slideDurationMs: 4200,
      transition: "soft-fade",
      animation: "fade",
      textStyle: "minimal",
      imageSlots: 8,
      overlay: { titlePosition: "top", pricePosition: "top", locationPosition: "bottom" },
      theme: { overlay: "white-minimal", titlePosition: "top", typography: "sans-bold", accent: "slate" },
      showPriceBadge: true,
      showChannelBranding: false,
    },
  },
  {
    slug: "luxury-agency-promo",
    name: "Luxury Agency Promo",
    type: "LONG",
    previewImage: svgPreview("Agency Promo", "#111827", "#4F46E5"),
    sortOrder: 8,
    config: {
      engineVersion: 1,
      duration: 55,
      slideDurationMs: 4700,
      transition: "elegant-slide",
      animation: "slide-left",
      textStyle: "luxury",
      kenBurns: true,
      imageSlots: 9,
      overlay: { titlePosition: "top", pricePosition: "bottom", locationPosition: "bottom" },
      theme: { overlay: "brand-strip", titlePosition: "top", typography: "sans-bold", accent: "indigo" },
      showPriceBadge: true,
      showChannelBranding: true,
    },
  },
  {
    slug: "architectural-flow-long",
    name: "Architectural Flow",
    type: "LONG",
    previewImage: svgPreview("Architectural Flow", "#0F172A", "#14B8A6"),
    sortOrder: 9,
    config: {
      engineVersion: 1,
      duration: 50,
      slideDurationMs: 5200,
      transition: "slide-fade",
      animation: "slide-right",
      textStyle: "minimal",
      kenBurns: true,
      imageSlots: 9,
      overlay: { titlePosition: "top", pricePosition: "bottom", locationPosition: "bottom" },
      theme: { overlay: "gradient-dark", titlePosition: "top", typography: "sans-bold", accent: "teal" },
      showPriceBadge: true,
      showChannelBranding: false,
    },
  },
  {
    slug: "imperial-estate-story",
    name: "Imperial Estate Story",
    type: "LONG",
    previewImage: svgPreview("Imperial Estate", "#1E1B4B", "#F59E0B"),
    sortOrder: 10,
    config: {
      engineVersion: 1,
      duration: 65,
      slideDurationMs: 6000,
      transition: "gold-fade",
      animation: "blur",
      textStyle: "luxury",
      kenBurns: true,
      grainOpacity: 0.03,
      imageSlots: 10,
      overlay: { titlePosition: "center", pricePosition: "bottom", locationPosition: "bottom" },
      theme: { overlay: "letterbox-film", titlePosition: "center", typography: "display-gold", accent: "amber" },
      showPriceBadge: true,
      showChannelBranding: true,
    },
  },
];
