import NextAuth, { NextAuthOptions } from "next-auth";import type { Account } from "next-auth";import CredentialsProvider from "next-auth/providers/credentials";import EmailProvider from "next-auth/providers/email";import GoogleProvider from "next-auth/providers/google";import FacebookProvider from "next-auth/providers/facebook";import { PrismaAdapter } from "@next-auth/prisma-adapter";import prisma from "@/lib/prisma";import bcrypt from "bcryptjs";import { userWherePhoneMatches } from "@/lib/userPhone";import { sendEmail } from "@/lib/email";
const googleConfigured =  Boolean(process.env.GOOGLE_CLIENT_ID?.trim()) &&  Boolean(process.env.GOOGLE_CLIENT_SECRET?.trim());
const facebookClientId =  process.env.FACEBOOK_CLIENT_ID?.trim() ||  process.env.FACEBOOK_APP_ID?.trim();const facebookClientSecret =  process.env.FACEBOOK_CLIENT_SECRET?.trim() ||  process.env.FACEBOOK_APP_SECRET?.trim();const facebookConfigured = Boolean(facebookClientId && facebookClientSecret);
// مش هنستخدم EMAIL_SERVER خلاصconst emailFrom = process.env.EMAIL_FROM?.trim();
/** Legacy accounts verified via phone OTP only (before email OTP). */function legacyPhoneVerifiedOnly(user: {  emailVerified: Date | null;  phoneVerified: boolean;  otpCode: string | null;  otpExpiresAt: Date | null;}): boolean {  return (    !user.emailVerified &&    user.phoneVerified &&    !user.otpCode &&    !user.otpExpiresAt  );}
export const authOptions: NextAuthOptions = {  adapter: PrismaAdapter(prisma),  providers: [    ...(emailFrom      ? [          EmailProvider({            server: {              host: "smtp.gmail.com",              port: 587,              auth: {                user: process.env.EMAIL_FROM,                pass: process.env.EMAIL_PASSWORD,              },            },            from: emailFrom!,            async sendVerificationRequest({ identifier, url }) {              try {                const host = new URL(url).host;
                await sendEmail({                  to: identifier,                  subject: `Sign in to ${host}`,                  html: `                    <p>Sign in to <strong>${host}</strong></p>                    <p><a href="${url}">Click here to sign in</a></p>                    <p>If you did not request this email, ignore it.</p>                  `,                });              } catch (err) {                console.error("Email error:", err);                throw new Error("Failed to send verification email");              }            },          }),        ]      : []),
    ...(googleConfigured      ? [          GoogleProvider({            clientId: process.env.GOOGLE_CLIENT_ID!,            clientSecret: process.env.GOOGLE_CLIENT_SECRET!,          }),        ]      : []),
    ...(facebookConfigured      ? [          FacebookProvider({            clientId: facebookClientId!,            clientSecret: facebookClientSecret!,          }),        ]      : []),
    CredentialsProvider({      name: "Credentials",      credentials: {        email: { label: "Email", type: "text" },        password: { label: "Password", type: "password" },      },      async authorize(credentials) {        if (!credentials?.email || !credentials?.password) {          throw new Error("Invalid credentials");        }
        const user = await prisma.user.findUnique({          where: { email: credentials.email },        });
        if (!user || !user.passwordHash) {          throw new Error("Invalid credentials");        }
        const isCorrectPassword = await bcrypt.compare(          credentials.password,          user.passwordHash        );
        if (!isCorrectPassword) {          throw new Error("Invalid credentials");        }
        if (!user.emailVerified && !legacyPhoneVerifiedOnly(user)) {          throw new Error(            "Please verify your email before signing in."          );        }
        return user;      },    }),
    CredentialsProvider({      id: "phone-login",      name: "Phone",      credentials: {        phone: { label: "Phone", type: "tel" },        email: { label: "Email", type: "text" },        loginToken: { label: "Login token", type: "text" },      },      async authorize(credentials) {        const raw = credentials?.phone?.trim();        const email = credentials?.email?.trim().toLowerCase();        const loginToken = credentials?.loginToken?.trim();
        if (!loginToken || (!raw && !email)) {          throw new Error("Missing data");        }
        let user = null;
        if (email) {          user = await prisma.user.findFirst({            where: {              email,              phoneLoginToken: loginToken,              phoneLoginTokenExpiresAt: { gt: new Date() },            },          });        } else {          const clause = userWherePhoneMatches(raw!);          if (!clause) throw new Error("Invalid phone");
          user = await prisma.user.findFirst({            where: {              AND: [                clause,                { phoneLoginToken: loginToken },                { phoneLoginTokenExpiresAt: { gt: new Date() } },                { phoneVerified: true },              ],            },          });        }
        if (!user) {          throw new Error("Invalid or expired login");        }
        await prisma.user.update({          where: { id: user.id },          data: {            phoneLoginToken: null,            phoneLoginTokenExpiresAt: null,          },        });
        return user;      },    }),  ],
  session: {    strategy: "jwt",  },
  pages: {    signIn: "/login",  },
  secret: process.env.NEXTAUTH_SECRET,};
const handler = NextAuth(authOptions);export { handler as GET, handler as POST };